<div class="container under-top">
        <ol class="breadcrumb">
                <li><a href="/<?php echo $projectId?>/issues">Zadania</a></li>
                <li class="active">Dodaj nowe zadanie</li>
        </ol>
</div>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
        <div class="container">
                <div class="center-block">
                        <?php
                        $form = $this->form;
                        if (!empty($parentId)) {
                        	$form->setAttribute('action', $this->url('AddChildIssue',array('project' => $projectId, 'id' => $parentId)));

                        } else {
                        	$form->setAttribute('action', $this->url('AddIssue',array('project' => $projectId)));
                        }
                        $form->setAttribute('class', 'form-horizontal');
                        $form->prepare();

                        echo $this->form()->openTag($form);
                        ?>
                                <div class="form-group">
                                         <?php echo $this->formLabel($form->get('subject')); ?>
                                        <div class="col-sm-10">
                                                <?php echo $this->formTextarea($form->get('subject')); ?>
                                        </div>
                                </div>
                                <div class="form-group">
                                        <?php echo $this->formLabel($form->get('project')); ?>
                                        <div class="col-sm-10">
                                                <?php echo $this->formSelect($form->get('project')); ?>
                                        </div>
                                </div>
                                <hr/>
                                <div class="form-group">
                                        <?php echo $this->formLabel($form->get('issueStatus')); ?>
                                        <div class="col-sm-10">
                                                <?php echo $this->formSelect($form->get('issueStatus')); ?>
                                        </div>
                                </div>
                                <div class="form-group">
                                        <?php echo $this->formLabel($form->get('issueTracker')); ?>
                                        <div class="col-sm-10">
                                                <?php echo $this->formSelect($form->get('issueTracker')); ?>
                                                <span class="help-block">Niektóre typy zadań są niedostępne w związku z definicją formularza lub ustawień przepływu.</span>
                                        </div>
                                </div>
                                <hr/>
                                <div class="form-group">
                                        <?php echo $this->formLabel($form->get('description')); ?>
                                        <div class="col-sm-10">
                                                <?php echo $this->formTextarea($form->get('description')); ?>
                                        </div>
                                </div>
                                <div class="form-group">
                                        <?php echo $this->formLabel($form->get('issuePriority')); ?>
                                        <div class="col-sm-10">
                                                <?php echo $this->formSelect($form->get('issuePriority')); ?>
                                        </div>
                                </div>
                                <!--
                                <div class="form-group">
                                        <?php /* echo $this->formLabel($form->get('issueAssigned')); */?>
                                        <div class="col-sm-10">
                                                <?php /* echo $this->formSelect($form->get('issueAssigned')); */?>
                                        </div>
                                </div>
                            -->
                                <div class="form-group">
                                        <div class="col-sm-10">
                                                <?php echo $this->formHidden($form->get('User')); ?>
                                        </div>
                                </div>
                                <hr/>

                                <div id="customFields">
                                	<?php foreach ($additionalFields as $field): ?>
                                		<div class="form-group">
		                                        <?php echo $this->formLabel($form->get($field->getName())); ?>
		                                        <div class="col-sm-10">
		                                                <?php 
		                                                	if($field->getType() == 'list'){
		                                                		echo $this->formSelect($form->get($field->getName()));
		                                                	}else if($field->getType() == 'text'){
		                                                		echo $this->formTextarea($form->get($field->getName()));
		                                                	} 
		                                                ?>
		                                        </div>
		                                </div>
                                	<?php endforeach; ?>
                                </div>
                                <br/>
                                <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                                <button type="submit" class="btn btn-success">Dodaj zadanie</button>
                                        </div>
                                </div>
                        <?php echo $this->form()->closeTag(); ?>
                </div>
        </div>
</div>