<div class="container under-top">
        <ol class="breadcrumb">
                <li><a href="/<?php echo $projectId?>/issues">Zadania</a></li>
                <li class="active">Edytuj zadanie</li>
        </ol>
</div>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
        <div class="container">
                <div class="center-block">
                        <?php
                        $form = $this->form;
                        $form->setAttribute('action', $this->url('EditIssue', array('id' => $issue->getId())));
                        
                        $form->setAttribute('class', 'form-horizontal');
                        $form->prepare();

                        echo $this->form()->openTag($form);
                        ?>
                                <div class="form-group">
                                        <?php echo $this->formLabel($form->get('project')); ?>
                                        <div class="col-sm-10">
                                                <?php echo $this->formSelect($form->get('project')); ?>
                                        </div>
                                </div>
                                <div class="form-group">
                                        <?php echo $this->formLabel($form->get('subject')); ?>
                                        <div class="col-sm-10">
                                                <?php echo $this->formSelect($form->get('subject')); ?>
                                                <span class="help-block">Niektóre typy zadań są niedostępne w związku z definicją formularza lub ustawień przepływu.</span>
                                        </div>
                                </div>
                                <hr/>
                                <div class="form-group">
                                        <?php echo $this->formLabel($form->get('description')); ?>
                                        <div class="col-sm-10">
                                                <?php echo $this->formTextarea($form->get('description')); ?>
                                        </div>
                                </div>
                                <div class="form-group">
                                        <?php echo $this->formLabel($form->get('issuePriority')); ?>
                                        <div class="col-sm-10">
                                                <?php echo $this->formSelect($form->get('issuePriority')); ?>
                                        </div>
                                </div>
                                <div class="form-group">
                                        <?php echo $this->formLabel($form->get('issueAssigned')); ?>
                                        <div class="col-sm-10">
                                                <?php echo $this->formSelect($form->get('issueAssigned')); ?>
                                        </div>
                                </div>
                                <div class="form-group">
                                        <div class="col-sm-10">
                                                <?php echo $this->formHidden($form->get('issueStatus')); ?>
                                                <?php echo $this->formHidden($form->get('User')); ?>
                                        </div>
                                </div>
                                <hr/>
                                <div class="form-group">
                                        <label for="inputCustomFields" class="col-sm-2 control-label">Dodatkowe pola</label>
                                        <div class="col-sm-10">
                                                <select class="form-control" id="inputCustomFields">
                                                        <option>Wybierz</option>
                                                        <option>Następnik</option>
                                                        <option>Opis klienta</option>
                                                        <option>Źródła pomocy</option>
                                                </select>
                                        </div>
                                </div>
                                <div id="customFields">
                                	<?php foreach ($additionalFields as $field): ?>
                                		<div class="form-group">
		                                        <?php echo $this->formLabel($form->get($field->getName())); ?>
		                                        <div class="col-sm-10">
		                                                <?php echo $this->formTextarea($form->get($field->getName())); ?>
		                                        </div>
		                                </div>
                                	<?php endforeach; ?>
                                </div>
                                <br/>
                                <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                                <button type="submit" class="btn btn-success">Edytuj zadanie</button>
                                        </div>
                                </div>
                        <?php echo $this->form()->closeTag(); ?>
                </div>
        </div>
</div>