<div class="container under-top">
        <div class="half-space-container">
                <ol class="breadcrumb">
                        <li class="active">Zadania</li>
                </ol>
        </div>
        <div class="half-space-container text-right">
                <form class="form-group form-inline" role="form">
                        <div class="form-group">
                                <label for="inputProject" class="control-label">Pokaż zadania dla&nbsp;</label>
                                <select class="form-control" id="inputProjectList">
                                        <optgroup label="Projekty">
                                        	<?php foreach ($this->projects as $project) { ?>
                                                <option value="<?php echo $project->getId() ?>" <?php if($this->id == $project->getId()){ echo "selected"; } ?>><?php echo $project->getName() ?></option>
                                            <?php } ?>
                                        </optgroup>
                                </select>
                        </div>
                </form>
        </div>
</div>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
        <div class="container">
            <div class="col-md-12 query-issue-list">
                <strong class="pull-left">Kwerendy:</strong>
                <ul class="list-unstyled">
                    <li class="pull-left"><a href="#">Tylko otwarte</a></li>
                    <li class="pull-left"><a href="#">Tylko przypisane do mnie</a></li>
                    <li class="pull-left"><a href="#">Do przejrzenia</a></li>
                </ul>
            </div>
            <div class="col-md-12 table-responsive table-background-white center-block">
                <table class="table table-hover table-clickable table-condensed">
                        <thead>
                                <tr>
                                        <th>Typ</th>
                                        <th>Klucz</th>
                                        <th>Priorytet</th>
                                        <th>Podsumowanie</th>
                                        <th>Os. przypisana</th>
                                        <th>Os. zgłaszająca</th>
                                        <th>Status</th>
                                        <th>Utworzono</th>
                                        <th>Zamknięto</th>
                                </tr>
                                <?php foreach ($this->issues as $issue) { ?>
                                <tr id="<?php echo $issue->getID() ?>">
                                    <td><?php echo $issue->getSubject() ?></td>
                                    <td>#<?php echo $issue->getID() ?></td>
                                    <td><?php echo $issue->getIssuePriority() ?></td>
                                    <td><?php echo (strlen($issue->getDescription()) > 28) ? substr($issue->getDescription(),0,25).'...' : $issue->getDescription();?></td>
                                    <td><?php if($issue->getTracker()){echo $issue->getTracker();}else{echo "brak";} ?></td>
                                    <td><?php echo $issue->getCreator()->getFirstName() . ' ' .  $issue->getCreator()->getLastName() ?></td>
                                    <td><?php echo $issue->getIssueStatus() ?></td>
                                    <td><?php echo date_format($issue->getCreationTime(), 'Y-m-d H:i:s') ?></td>
                                    <td><?php if($issue->getCloseTime()){echo date_format($issue->getCloseTime(), 'Y-m-d H:i:s');}else{echo "Otwarte";} ?></td>
                                </tr>
                                <?php } ?>
                        </thead>
                        <tbody>

                        </tbody>
                </table>
            </div>
        </div>
</div>

