<div class="container under-top">
        <div class="half-space-container">
                <ol class="breadcrumb">
                        <li class="active">Zadania</li>
                </ol>
        </div>
        <div class="half-space-container text-right">
                <form class="form-group form-inline" role="form">
                        <div class="form-group">
                                <label for="inputProject" class="control-label">Pokaż zadania dla&nbsp;</label>
                                <select class="form-control" id="inputProject">
                                        <optgroup label="Ostatnio wybierane projekty">
                                                <option>Projekt testowy</option>
                                                <option>Most recent one</option>
                                        </optgroup>
                                        <optgroup label="Pozostałe">
                                                <option>Another recent project</option>
                                        </optgroup>
                                </select>
                        </div>
                </form>
        </div>
</div>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
        <div class="container">
            <div class="col-md-10 table-responsive table-background-white center-block">
                <table class="table table-hover table-clickable table-condensed">
                        <thead>
                                <tr>
                                        <th>Typ</th>
                                        <th>Klucz</th>
                                        <th>Priorytet</th>
                                        <th>Podsumowanie</th>
                                        <th>Os. przypisana</th>
                                        <th>Os. zgłaszająca</th>
                                        <th>Status</th>
                                        <th>Utworzono</th>
                                        <th>Zamknięto</th>
                                </tr>
                                <?php foreach ($this->issues as $issue) { ?>
                                <tr id="<?php echo $issue->getID() ?>">
                                    <td><?php echo $issue->getSubject() ?></td>
                                    <td>#<?php echo $issue->getID() ?></td>
                                    <td><?php echo $issue->getIssuePriority() ?></td>
                                    <td><?php echo $issue->getDescription() ?></td>
                                    <td><?php echo $issue->getTracker() ?></td>
                                    <td><?php echo $issue->getCreator() ?></td>
                                    <td><?php echo $issue->getIssueStatus() ?></td>
                                    <td><?php echo date_format($issue->getCreationTime(), 'Y-m-d H:i:s') ?></td>
                                    <td><?php if($issue->getCloseTime()){echo date_format($issue->getCloseTime(), 'Y-m-d H:i:s');} ?></td>
                                </tr>
                                <?php } ?>
                        </thead>
                        <tbody>

                        </tbody>
                </table>
            </div>
            <div class="col-md-2">
                <strong>Kwerendy</strong>
                <ul class="list-unstyled">
                    <li><a href="#">Tylko otwarte</a></li>
                    <li><a href="#">Tylko przypisane do mnie</a></li>
                    <li><a href="#">Do przejrzenia</a></li>
                </ul>
            </div>
        </div>
</div>

