<div class="container under-top">
        <div class="half-space-container">
                <ol class="breadcrumb">
                        <li class="active">Zadania</li>
                </ol>
        </div>
        <div class="half-space-container text-right">
                <form class="form-group form-inline" role="form">
                        <div class="form-group">
                                <label for="inputProject" class="control-label">Pokaż zadania dla&nbsp;</label>
                                <select class="form-control" id="inputProjectList">
                                        <optgroup label="Projekty">
                                        	<?php foreach ($this->projects as $project) { ?>
                                                <option value="<?php echo $project->getId() ?>" <?php if($this->id == $project->getId()){ echo "selected"; } ?>><?php echo $project->getName() ?></option>
                                            <?php } ?>
                                        </optgroup>
                                </select>
                        </div>
                </form>
        </div>
</div>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
        <div class="container">
            <div class="col-md-12 query-issue-list">
                <strong class="pull-left">Kwerendy:</strong>
                <ul class="list-unstyled">
                    <li class="pull-left"><a href="#">Tylko otwarte</a></li>
                    <li class="pull-left"><a href="#">Tylko przypisane do mnie</a></li>
                    <li class="pull-left"><a href="#">Do przejrzenia</a></li>
                </ul>
            </div>
            <div class="col-md-12 table-responsive table-background-white center-block">
                <table class="table table-hover table-clickable issues-list-table table-condensed">
                        <thead>
                                <tr>
                                        <th>Typ</th>
                                        <th>Priorytet</th>
                                        <th>Status</th>
                                        <th>Podsumowanie</th>
                                        <th>Os. przypisana</th>
                                        <th>Os. zgłaszająca</th>
                                        <th>Utworzono</th>
                                        <th>Zamknięto</th>
                                        <th>Klucz</th>
                                </tr>
                        </thead>
                        <tbody>
                                <?php foreach ($this->issues as $issue) { 
                                    if(!$issue->getParent()){?>
                                <tr id="<?php echo $issue->getID() ?>" style="background:#F8F8F8;">
                                    <td><span class="label label-default <?php echo "label-".$issue->getTracker() ?>">
                                        <?php echo $issue->getTracker() ?>
                                        </span>
                                    </td>
                                    <td><?php echo $issue->getIssuePriority() ?></td>
                                    <td><?php echo $issue->getIssueStatus() ?></td>
                                    <td><b><?php echo $issue->getSubject()?></b></td>
                                    <td><?php foreach ($issue->getAssignedUsers() as $user){
                                                    $userName = $user->getFirstName()  . ' ' .  $user->getLastName() . '<br>';
                                                    if(!empty($user)){
                                                        echo $userName;
                                                    }else{
                                                        echo "brak";
                                                    }
                                              }?></td>
                                    <td><?php echo $issue->getCreator()->getFirstName() . ' ' .  $issue->getCreator()->getLastName() ?></td>
                                    <td><?php echo date_format($issue->getCreationTime(), 'Y-m-d H:i:s') ?></td>
                                    <td><?php if($issue->getCloseTime()){echo date_format($issue->getCloseTime(), 'Y-m-d H:i:s');}else{echo "Otwarte";} ?></td>
                                    <td>#<?php echo $issue->getID() ?></td>
                                </tr>
                                <?php } foreach ($this->issues as $issueChild) {
                                    if($issueChild->getParent()){
                                        if($issue->getId() == $issueChild->getParent()->getId()){ ?>
                                            <tr id="<?php echo $issueChild->getID() ?>">
                                        <td><span class="label label-default <?php echo "label-".$issueChild->getTracker() ?>">
                                            <?php echo $issueChild->getTracker() ?>
                                            </span>
                                        </td>
                                        <td><?php echo $issueChild->getIssuePriority() ?></td>
                                        <td><?php echo $issueChild->getIssueStatus() ?></td>
                                        <td><b><?php echo $issueChild->getSubject()?></b></td>
                                        <td><?php foreach ($issueChild->getAssignedUsers() as $user){
                                                        $userName = $user->getFirstName()  . ' ' .  $user->getLastName() . '<br>';
                                                        if(!empty($user)){
                                                            echo $userName;
                                                        }else{
                                                            echo "brak";
                                                        }
                                                  }?></td>
                                        <td><?php echo $issueChild->getCreator()->getFirstName() . ' ' .  $issueChild->getCreator()->getLastName() ?></td>
                                        <td><?php echo date_format($issueChild->getCreationTime(), 'Y-m-d H:i:s') ?></td>
                                        <td><?php if($issueChild->getCloseTime()){echo date_format($issueChild->getCloseTime(), 'Y-m-d H:i:s');}else{echo "Otwarte";} ?></td>
                                        <td>#<?php echo $issueChild->getID() ?></td>
                                    </tr>
                                <?php } } } ?>
                                <?php } ?>
                        </tbody>
                </table>
            </div>
        </div>
</div>

