<div class="container under-top">
        <ol class="breadcrumb">
                <li><a href="/<?php echo $issue->getProject() ?>/issues">Zadania</a></li>
                <li><a href="?page=ProjectOverview"><?php echo $issue->getProject()->getName() ?></a></li>
                <li class="active">#<?php echo $issue->getID() ?></li>
        </ol>

</div>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron jumbotron-padding-top-10">
    <div class="container">
        <div class="center-block">
            <nav class="navbar navbar-default navbar-margin-top" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header">

                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
                            <span class="sr-only">Zarządzaj</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>

                        </button>
                        <span class="navbar-brand brand">
                            <span class="label label-default <?php echo "label-".$issue->getSubject() ?> label-show-task">
                                        <?php echo $issue->getSubject() ?>
                                        </span>
                                         <?php echo (strlen($issue->getDescription()) > 53) ? substr($issue->getDescription(),0,50).'...' : $issue->getDescription();?></span>
                    </div>
                    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-2">
                        <a href="/issue/<?php echo $issue->getID() ?>/edit">
                            <button type="button" class="btn btn-default navbar-btn">Edycja</button>
                        </a>
                        <button type="button" class="btn btn-default navbar-btn">Przydziel osobę</button>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                Więcej <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Utwórz podzadanie</a></li>
                                <li><a href="#">Zmień w podzadanie</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Przenieś</a></li>
                                <li><a href="#">Skopiuj do innego projektu</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <!-- Nav tabs -->
        <ul class="nav nav-tabs">
            <li class="active"><a href="#home" data-toggle="tab">Szczegóły</a></li>
            <li><a href="#profile" data-toggle="tab">Historia zmian</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content tab-content-white">
            <div class="tab-pane active" id="home">
                    <div class="col-md-3 col-md-3"><h3><span class="glyphicon glyphicon-info-sign"></span> Szczegóły</h3></div>
                    <div class="col-md-1 col-md-3 details-label upper-desc">Priorytet:</div>
                    <div class="col-md-2 col-md-6 upper-desc"><?php echo $issue->getIssuePriority() ?></div>
                    <div class="col-md-1 col-md-3 details-label upper-desc">Typ:</div>
                    <div class="col-md-2 col-md-6 upper-desc"><?php echo $issue->getSubject() ?></div>
                    <div class="col-md-1 col-md-3 details-label upper-desc">Status:</div>
                    <div class="col-md-1 col-md-6 upper-desc"><?php echo $issue->getIssueStatus() ?></div>
                    <div class="row show-grid row-with-space">
                    </div>
                    <div class="well"><?php echo $issue->getDescription() ?></div>
                    <div class="row show-grid row-with-space">
                    </div>
                    <div class="col-md-6 col-md-6">
                        <h3><span class="glyphicon glyphicon-user"></span> Osoby</h3>
                        <div class="row show-grid row-with-space">
                            <div class="col-md-4 col-md-4 details-label">Utworzone przez:</div>
                            <div class="col-md-6 col-md-6"><?php echo $issue->getCreator()->getFirstName() . ' ' .  $issue->getCreator()->getLastName() ?></div>
                            <div class="row show-grid row-with-space">
                            </div>
                            <div class="col-md-4 col-md-4 details-label">Przypisane osoby:</div>
                            <div class="col-md-6 col-md-6"><?php if($issue->getTracker()){echo $issue->getTracker();}else{echo "brak";} ?></div>
                        </div>
                    </div>
                    <div class="col-md-6 col-md-6">
                        <h3><span class="glyphicon glyphicon-calendar"></span> Daty</h3>
                        <div class="row show-grid row-with-space">
                            <div class="col-md-4 col-md-4 details-label">Data utworzenia:</div>
                            <div class="col-md-6 col-md-6"><?php echo date_format($issue->getCreationTime(), 'Y-m-d H:i:s') ?></div>
                            <div class="row show-grid row-with-space">
                            </div>
                            <div class="col-md-4 col-md-4 details-label">Data zamknięcia:</div>
                            <div class="col-md-6 col-md-6"><?php if($issue->getCloseTime()){echo date_format($issue->getCloseTime(), 'Y-m-d H:i:s');}else{echo "Wciąż Otwarte";} ?></div>
                        </div>
                    </div>
                     <div class="row show-grid row-with-space">
                            </div>
                </div>
                <div class="tab-pane" id="profile">...</div>
            </div>
        </div>
    </div>
</div>
</div>