<style>
    li.header{
        margin-top: 20px;
    }
    .center-block.table-responsive.table-background-white {
padding-bottom: 20px;
}
</style>
    
	<div class="jumbotron">
        <ol class="breadcrumb container change-pos">                                 
            <li class="active header"></li>                                    
        </ol>  
            
		<div class="container">
			<div class="center-block table-responsive table-background-white" >
                
                            
                <div class="center-block">
                    <div ng-controller="Ctrl">
                        <h3>Statusy zagadnień</h3>
				    <table class="table table-striped table-clickable">
                        <thead>
                            <tr>
                                <th style="width: 20%">Nazwa</th>
                                <th style="width: 20%">Domyślna Wartość</th>
                                <th style="width: 30%">Możliwe Wartości</th>
                                <th style="width: 15%"></th>
                                <th style="width: 15%">Akcja</th>
                            </tr>
                        </thead>
                                          
                        <tbody>
                        <!-- TODO: lista slownikow -->
                        </tbody>
                        
                    </table>
                       
                    
                    </div>
			
                </div>
                           
			</div>
		</div>
            
      
            
	</div>



    


