<?php
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>

<div class="container under-top">
        <ol class="breadcrumb">
                <li><a href="?page=ListOfTasks">Zadania</a></li>
                <li><a href="?page=ViewTask">#BUG-1</a></li>
                <li><a href="?page=ListTimeEntry">Czas pracy</a></li>
                <li class="active">Dodaj czas pracy</li>
        </ol>
</div>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
        <div class="container">
                <div class="center-block">
                    <?php echo $this->form()->openTag($form); ?>
                    
                    <input type="hidden" name="issueId" value="<?php echo $issue->getId() ?>" />
                    
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('hours')) ?>
                        <div class="col-sm-10">
                            <?php echo $this->formNumber($form->get('hours')) ?>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('comment')) ?>
                        <div class="col-sm-10">
                            <?php echo $this->formTextarea($form->get('comment')) ?>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('entryDate')) ?>
                        <div class="col-sm-10">
                            <?php echo $this->formDateTimeLocal($form->get('entryDate')) ?>
                        </div>
                    </div>
                    
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Dodaj czas pracy</button>
                        <a href="<?php echo $this->url('WorkTimeEntry-Issue', array('issueId' => $issue->getId())) ?>" class="btn btn-default">Anuluj</a>
                    </div>
                    
                    <?php echo $this->form()->closeTag(); ?>
                </div>
        </div>
</div>