<style>
    li.header{
        margin-top: 20px;
    }
   input[type=text] {
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.428571429;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    }
    textarea {
        width: 300px;
        max-width: 300px;
        min-width: 300px;
        min-height: 34px;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.428571429;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    }
    p.bg-danger{
        font-size: 14px;
        padding: 10px;
    }
</style>
    
	<div class="jumbotron">
        <ol class="breadcrumb container change-pos">                                 
            <li class="active header">Statusy zagadnień</li>                                    
        </ol>  
		<div class="container">
			<div class="center-block table-responsive table-background-white" >
                 <?php 
                       $form = $this->form;                      
                       $form->prepare();
                       
                       echo $this->form()->openTag($form);
                       
                       
                       ?>
                            
                <div class="center-block">
                    <div ng-app="app" ng-controller="Ctrl">
                    <p class="bg-danger <?php echo $ex?>">Uwaga! Status nie może być jednocześnie otwarty i zamknięty.</p>  
          
				    <table class="table table-striped table-clickable">
                        <thead>
                            <tr>
                                <th style="width: 25%">Status</th>
                                <th style="width: 45%">Opis</th>
                                <th style="width: 10%">Domyślny Status</th>
                                <th style="width: 10%">Zagadnienia zamknięte</th>
                                <th style="width: 10%">Zagadnienia otwarte</th>

                            </tr>
                        </thead>
                       
                        <tbody>
                            <tr ng-repeat="status in statuses" class="ng-scope">
                                <td>
                                    <span editable-text="status.name" e-name="name" e-form="rowform" onbeforesave="checkName($data, status.id)" e-required="" class="ng-scope ng-binding editable editable-hide editable-empty">
                                    
                                    </span>
                                    <span class="editable-wrap editable-text ng-scope">
                                        <div class="editable-controls form-group" ng-class="{'has-error': $error}">
                                            <div class="col-sm-13">
                                                <?php echo $this->formElement($form->get('name')); ?>
                                            </div>
                                            <div class="editable-error help-block ng-binding" ng-show="$error" ng-bind="$error" style="display: none;">                                                
                                            </div>                                            
                                        </div>
                                    </span>
                                </td>
                                <td>
                                 <td>
                                    <span editable-text="status.name" e-name="name" e-form="rowform" onbeforesave="checkName($data, status.id)" e-required="" class="ng-scope ng-binding editable editable-hide editable-empty">
                                    
                                    </span>
                                    <span class="editable-wrap editable-text ng-scope">
                                        <div class="editable-controls form-group" ng-class="{'has-error': $error}">
                                            <div class="col-sm-13">
                                                <?php echo $this->formElement($form->get('description')); ?>
                                            </div>
                                            <div class="editable-error help-block ng-binding" ng-show="$error" ng-bind="$error" style="display: none;">                                                
                                            </div>                                            
                                        </div>
                                    </span>
                                </td>
                                    <span editable-checkbox="status.default" e-name="default" e-form="rowform" onbeforesave="checkName($data, default.id)" class="ng-scope ng-binding editable editable-hide editable-empty">
                                    
                                    </span>
                                    <span class="editable-wrap editable-checkbox ng-scope">
                                        <div class="editable-controls form-group" ng-class="{'has-error': $error}">
                                            <?php echo $this->formRow($form->get('IsDefault')); ?> 
                                        </div> 
                                        
                                    </span>
                                </td>
                                <td>
                                    <span editable-checkbox="status.close" e-name="default" e-form="rowform" onbeforesave="checkName($data, close.id)" class="ng-scope ng-binding editable editable-hide editable-empty">
                                    
                                    </span>
                                    <span class="editable-wrap editable-checkbox ng-scope">
                                        <div class="editable-controls form-group" ng-class="{'has-error': $error}">
                                            <?php echo $this->formRow($form->get('IsClosed')); ?> 
                                            <div class="editable-error help-block ng-binding" ng-show="$error" ng-bind="$error" style="display: none;">                                                
                                            </div>                                                
                                        </div>
                                    </span>
                                </td>
                                <td>
                                     <span editable-checkbox="status.close" e-name="default" e-form="rowform" onbeforesave="checkName($data, close.id)" class="ng-scope ng-binding editable editable-hide editable-empty">
                                    
                                    </span>
                                    <span class="editable-wrap editable-checkbox ng-scope">
                                        <div class="editable-controls form-group" ng-class="{'has-error': $error}">
                                            <?php echo $this->formRow($form->get('IsActive')); ?> 
                                            <div class="editable-error help-block ng-binding" ng-show="$error" ng-bind="$error" style="display: none;">                                                
                                            </div>                                                
                                        </div>
                                    </span>
                                </td>
                                
                                
                            </tr>
                        </tbody>
                        
                    </table>
                    <button type="submit" class="btn btn-success" ng-click="addstatus()"><i class="fa fa-plus-circle"></i> Stwórz status</button>
                    
                    </div>
			
                </div>
                 <?php echo $this->form()->closeTag(); ?>           
			</div>
		</div>
	</div>


	




