<style>
    li.header{
        margin-top: 20px;
    }
     textarea {
        width: 300px;
        max-width: 300px;
        min-width: 300px;
        min-height: 34px;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.428571429;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    }
    p.bg-danger{
        font-size: 14px;
        padding: 10px;
    }
</style>
    
	<div class="jumbotron">
        <ol class="breadcrumb container change-pos">                                 
            <li class="active header"></li>                                    
        </ol>  
            
		<div class="container">
			<div class="center-block table-responsive table-background-white" >
                <?php 
                       $form = $this->form2;                      
                       $form->prepare();
                       
 
                        echo $this->form()->openTag($form);

                       ?>
                            
                <div class="center-block">
                    <div ng-app="app" ng-controller="Ctrl">
                    <p class="bg-danger <?php echo $ex?>">Uwaga! Status nie może być jednocześnie aktywny i zamknięty.</p>  
			
			<table class="table table-striped table-clickable">
                        <thead>
                            <tr>
                                <th style="width: 35%">Status</th>
                                <th style="width: 45%">Opis</th>
                                <th style="width: 25%">Domyślny Status</th>
                                <th style="width: 10%">Zagadnienie zamknięte</th>
                                <th style="width: 10%">Zagadnienie aktywne</th>
                                
                            </tr>
                        </thead>
                       
                        <tbody>                         
                               <tr>
		                <td>
                                  <div class="editable-controls form-group">
                                      <input type="text" name="name" required="required" value="<?php echo  $issueedit->getName('id')?>" class="editable-input form-control ng-pristine ng-invalid ng-invalid-required" ng-model="$data">                                    
                                  </div>
                                </td>
                                <td>
                                  <div class="editable-controls form-group">
                                      <textarea name = "description" placeholder='Opis statusu...'><?php echo  $issueedit->getDescription('id')?></textarea>     
                                     
                                  </div>
                                </td>
		                <td>
                                    
                                    <span class="editable-wrap editable-checkbox ">
                                        <div class="editable-controls form-group">
                                            <?php echo $this->formRow($form->get('IsDefault')->setChecked($issueedit->getIsDefault())); ?>                                            
                                            <div class="editable-error help-block ng-binding" ng-show="$error" ng-bind="$error" style="display: none;">                                                
                                            </div>                                                
                                        </div>
                                    </span>
                                </td>
                                <td>
                                    <span editable-checkbox="status.close" e-name="default" e-form="rowform" onbeforesave="checkName($data, close.id)" class="ng-scope ng-binding editable editable-hide editable-empty" />
                              </span>
                                    <span class="editable-wrap editable-checkbox ng-scope">
                                        <div class="editable-controls form-group">
                                            <?php echo $this->formRow($form->get('IsClosed')->setChecked($issueedit->getIsClosed())); ?> 
                                            <div class="editable-error help-block ng-binding" ng-show="$error" ng-bind="$error" style="display: none;">                                                
                                            </div>                                                
                                        </div>
                                    </span>
                                </td>
                                <td>
                                  <input name="position" type="hidden" value="<?php echo $issueedit->getPosition('id'); ?>   ">                                                                                    
                                  <span class="editable-wrap editable-checkbox ">
                                        <div class="editable-controls form-group">
                                            <?php echo $this->formRow($form->get('IsActive')->setChecked($issueedit->getIsActive())); ?>                                            
                                            <div class="editable-error help-block ng-binding" ng-show="$error" ng-bind="$error" style="display: none;">                                                
                                            </div>                                                
                                        </div>
                                    </span>
                                </td>
                            </tr>
                                                
                        </tbody>
                        
                    </table>
                         <button type="submit" class="btn btn-success"><i class="fa fa-plus-circle"></i> Zaktualizuj status</button>
                    
                    </div>
			<?php 
                        
                        
                        echo $this->form()->closeTag(); ?>    
                </div>
                           
			</div>
		</div>
            
	</div>



    


