<style>
    li.header{
        margin-top: 20px;
    }
    .center-block.table-responsive.table-background-white {
padding-bottom: 20px;
}
tr:first-of-type i.fa.fa-sort-desc, tr:last-of-type i.fa.fa-sort-asc{
    cursor: not-allowed;
}
td p{
    width: 300px;
white-space: nowrap;
text-overflow: ellipsis;
text-align: center;
overflow: hidden;
font-size: 14px!important;
margin: 0px!important
}
p.bg-danger{
        font-size: 14px;
        padding: 10px;
}
</style>
    
	<div class="jumbotron">
        <ol class="breadcrumb container change-pos">                                 
            <li class="active header"></li>                                    
        </ol>  
            
		<div class="container">
			<div class="center-block table-responsive table-background-white" >
                
                            
                <div class="center-block">
                    <div ng-controller="Ctrl">

                        <h3>Statusy zagadnień</h3>
                        <p class="bg-danger <?php echo $ex?>">Uwaga! Ten status przypisany jest do części zagadnień i nie może zostać usunięty.</p>
				    <table class="table table-striped table-clickable">
                        <thead>
                            <tr>
                               	<th style="width: 20%">Status</th>
                                <th style="width: 30%">Opis</th>
                                <th style="width: 10%">Domyślny Status</th>
                                <th style="width: 10%">Zagadnienia zamknięte</th>
                                <th style="width: 10%">Zagadnienia aktywne</th>
                                <th style="width: 10%">Sortuj</th>
                                <th style="width: 10%">Akcja</th>
                            </tr>
                        </thead>
                                          
                        <tbody>
                            <?php foreach($issuelist as $issue) {
                               
                          
                          
                          if($issue->getIsClosed(true)){
                            $closed = '<i class="fa fa-check"></i>';
                          }

                                                 echo '<tr>
		                        <td>'. $issue->getName('id').' </td> 
		                         <td><p>'. $issue->getDescription('id').'</p> </td> 
		                      <td>
                                    
                                    <span class="editable-wrap editable-checkbox ng-scope">
                                        <div class="editable-controls form-group">
                                           '. $issue->getIsDefault().'
                                            
                                           <div class="editable-error help-block ng-binding" ng-show="$error" ng-bind="$error" style="display: none;">                                                
                                           
                                            </div>                                                
                                        </div>
                                    </span>
                                </td>
                                <td>
                                    <span editable-checkbox="status.close" e-name="default" e-form="rowform" onbeforesave="checkName($data, close.id)" class="ng-scope ng-binding editable editable-hide editable-empty">
                                    
                                    </span>
                                    <span class="editable-wrap editable-checkbox ng-scope">
                                        <div class="editable-controls form-group">
                                            '. $issue->getIsClosed().'
                                            <div class="editable-error help-block ng-binding" ng-show="$error" ng-bind="$error" style="display: none;">                                                
                                            </div>                                                
                                        </div>
                                    </span>
                                </td>
                                 <td>
                                    <span editable-checkbox="status.close" e-name="default" e-form="rowform" onbeforesave="checkName($data, close.id)" class="ng-scope ng-binding editable editable-hide editable-empty">
                                    
                                    </span>
                                    <span class="editable-wrap editable-checkbox ng-scope">
                                        <div class="editable-controls form-group">
                                            '. $issue->getIsActive().'
                                            <div class="editable-error help-block ng-binding" ng-show="$error" ng-bind="$error" style="display: none;">                                                
                                            </div>                                                
                                        </div>
                                    </span>
                                </td>
                                 <td>
                                    <a href="'  . $this->url('DownIssueStatus', array('action'=>'down', 'id'=>$issue->getId())). '"><i class="fa fa-sort-asc"></i></a>
                                    <a href="'  . $this->url('UpIssueStatus', array('action'=>'up', 'id'=>$issue->getId())). '"><i class="fa fa-sort-desc"></i></a>
                                </td>
		                 <td style="white-space: nowrap">
                                    <form editable-form="" name="rowform" onbeforesave="save($data, status.id)" ng-show="rowform.$visible" class="form-buttons form-inline ng-pristine ng-valid" shown="inserted == status">
                                        <a href="'  . $this->url('UpdateIssueStatus', array('action'=>'edit', 'id'=>$issue->getId())). '" class="btn btn-primary"><i class="fa fa-pencil-square-o"></i></a>
                                        <a href="'  . $this->url('DeleteIssueStatus', array('action'=>'delete', 'id'=>$issue->getId())). '"><button type="button" ng-disabled="rowform.$waiting" ng-click="rowform.$cancel()" class="btn btn-danger"><i class="fa fa-trash-o"></i></button> </a>
                                    </form>
                                     
                                </td>       

                            </tr>';
                                                }?>
                        </tbody>
                        
                    </table>
                         <a href="<?php echo $this->url('AddIssueStatus') ?>"><button type="submit" class="btn btn-success" ng-click="addstatus()"><i class="fa fa-plus-circle"></i> Stwórz status</button></a>
                    
                    </div>
			
                </div>
                           
			</div>
		</div>
            
      
            
	</div>



    


