	<script>
		function test(){
			alert("SIEMA");
		};
		function zaznaczacz(){
			var checkboxes = new Array(); 
			checkboxes = document.getElementsByTagName('input');
			 
			for (var i=0; i<checkboxes.length; i++)  {
				if (checkboxes[i].type == 'checkbox')   {
				  checkboxes[i].checked = false;
				}
			}
			
			var trID = document.getElementById("tracker").value;
			//alert(trID);
			var mrID = document.getElementById("memberRole").value;
			//alert(mrID);
			var divContent = document.getElementById("trzymacz").innerHTML;
			//alert(divContent);
			var transitiony = divContent.split("<br>");
			//alert("tu jestem");
			//alert(transitiony.length);
			for (index = 0; index < transitiony.length; ++index) {
				var temp = transitiony[index].split(",");
				if(temp[0] == trID){
					if(temp[1] == mrID){
						//alert("dzien dobry");
						document.getElementById(temp[2]).checked = true;
					}
				}
			}
		};
    </script>
	
	<div class="container">
		<ol class="breadcrumb">
			<li><a href="#">Strona Główna</a></li>
            		<li class="active">Przejścia stanów</li>
		</ol>
	</div>
	<!-- Main jumbotron for a primary marketing message or call to action -->
	<form method='POST'>
	<div class="jumbotron">
	
        <ol class="breadcrumb container change-pos">                                 
            <li class="active">Przejścia stanów </li>  
	<br>
		
	<br>
		<div class="half-space-container text-left">
                <form class="form-group form-inline" role="form">
                        <div class="form-group">
                                <label for="memberRole" class="control-label">Rola:</label>
                                <select class="form-control" name="memberRole" id="memberRole" onchange="zaznaczacz()">
									<?php
										foreach($roleList as $rola){
											echo "<option value=" . $rola->getId();
											if (isset($_POST['memberRole'])) {
												if($_POST['memberRole'] == $rola->getId()) {
													echo " selected";
												}
											}
											echo ">" . $rola->getName() . "</option>";
										}
									?>
                                </select>
                        </div>

                        <div class="form-group">
                                <label for="tracker" class="control-label">&nbsp;Typ zagadnienia:&nbsp;</label>
                                <select class="form-control" name="tracker" id="tracker" onchange="zaznaczacz()">
									<?php
										foreach($trackerList as $track){
											echo "<option value=" . $track->getId();
											if (isset($_POST['tracker'])) {
												if($_POST['tracker'] == $track->getId()) {
													echo " selected";
												}
											}
											echo ">" . $track->getName() . "</option>";
										}
									?>
                                </select>
                        </div>

                </form>
      		</div>
			<?php 
			if(isset($_POST['tracker'])){
				$czyOk = $controler->addNewStatusTransition($_POST);
				if($czyOk == "OK") {
				$_POST['tracker'] = '';
				echo "<script>
							var trID = document.getElementById('tracker').selectedIndex ;
							var mrID = document.getElementById('memberRole').selectedIndex ;
							localStorage.setItem('track', trID);
							localStorage.setItem('role', mrID);";
							if (strstr($_SERVER['HTTP_USER_AGENT'], "Firefox")){
								echo " window.location.href = window.location.href; ";
							}
							else {
								echo " location.reload(); ";
							}
							//
							
						echo "</script>;";
				}
			}?>
			<script>
			if(localStorage.getItem('track') != ''){
				document.getElementById("memberRole").selectedIndex = localStorage.getItem('role');
				document.getElementById("tracker").selectedIndex = localStorage.getItem('track');
				//localStorage.setItem('track', '');
				//localStorage.setItem('role', '');
			}		
			</script>
			


                                  
        </ol>  
		<div class="container">
			<div class="center-block table-responsive table-background-white" >
                <div class="center-block">
                    <div ng-app="app" ng-controller="Ctrl">
				    <table class="table table-striped">
                        
			
			<thead>
                            <tr class="breadcrumb">
							<th></th>
                                <?php
									foreach($issuelist as $issue){
										echo "<th>" . $issue->getName() . "</th>";
									}
								?>
								
                            </tr>
							<?php
								foreach($issuelist as $issue){
									echo "<tr>
									<th class='breadcrumb'>" . $issue->getName() . "</th>";			
									foreach($issuelist as $issueStatus){
										echo "<th><input type='checkbox' name='check_list[]' value=" . $issue->getId() . "-" .$issueStatus->getId(). " id='" . $issue->getId() . "-" .$issueStatus->getId(). "'> </th>";//" . $issueStatus->getName() . " value: lewe-prawe	visibility: hidden
									}
									echo "</tr>";
								}
							?>
			    
                        </thead>

                    </table>
					<a href="<?php echo $this->url('statusTransiton') ?>"><button class="btn btn-success">Zapisz</button></a>
                    </div>
			     </div>
			</div>
		</div>
	</div>
	</form>
	<div style="display: none;" id="trzymacz">
	<?php //display: none
		foreach($przejscia as $przej){
			echo $przej->getTracker()->getId() . "," . $przej->getMemberRole()->getId() . "," . $przej->getPrevStatus()->getId() . "-" . $przej->getNextStatus()->getId() . "<br>";
		}
	?>
	</div>
	
	<script>
		zaznaczacz();
	/*
		var trID = document.getElementById("tracker").value;
		alert(trID);
		var mrID = document.getElementById("memberRole").value;
		alert(mrID);
		var divContent = document.getElementById("trzymacz").innerText;
		var transitiony = divContent.split(";\n");
		for (index = 0; index < transitiony.length; ++index) {
			console.log(transitiony[index]);
		}
	*/
	</script>
