	<div class="container">
		<ol class="breadcrumb">
			<li><a href="#">Strona Główna</a></li>
            		<li class="active">Przejścia stanów</li>
		</ol>
	</div>
	<!-- Main jumbotron for a primary marketing message or call to action -->
	<form method='POST'>
	<div class="jumbotron">
	
        <ol class="breadcrumb container change-pos">                                 
            <li class="active">Przejścia stanów </li>  
	<br>
	<?php if(isset($_POST['tracker'])){
			echo $controler->addNewStatusTransition($_POST);			
		}
		
	?>
	<br>
		<div class="half-space-container text-left">
                <form class="form-group form-inline" role="form">
                        <div class="form-group">
                                <label for="memberRole" class="control-label">Rola:</label>
                                <select class="form-control" name="memberRole" id="memberRole">
									<?php
										foreach($roleList as $rola){
											echo "<option value=" . $rola->getId() . ">" . $rola->getName() . "</option>";
										}
									?>
                                </select>
                        </div>

                        <div class="form-group">
                                <label for="tracker" class="control-label">&nbsp;Typ zagadnienia:&nbsp;</label>
                                <select class="form-control" name="tracker" id="tracker">
									<?php
										foreach($trackerList as $track){
											echo "<option value=" . $track->getId() . ">" . $track->getName() . "</option>";
										}
									?>
                                </select>
                        </div>

                </form>
      		</div>


                                  
        </ol>  
		<div class="container">
			<div class="center-block table-responsive table-background-white" >
                <div class="center-block">
                    <div ng-app="app" ng-controller="Ctrl">
				    <table class="table table-striped">
                        
			
			<thead>
                            <tr class="breadcrumb">
							<th></th>
                                <?php
									foreach($issuelist as $issue){
										echo "<th>" . $issue->getName() . "</th>";
									}
								?>
								
                            </tr>
							<?php
								foreach($issuelist as $issue){
									echo "<tr>
									<th class='breadcrumb'>" . $issue->getName() . "</th>";			
									foreach($issuelist as $issueStatus){
										echo "<th><input type='checkbox' name='check_list[]' value=" . $issue->getId() . "-" .$issueStatus->getId(). "> </th>";//" . $issueStatus->getName() . " value: lewe-prawe
									}
									echo "</tr>";
								}
							?>
			    
                        </thead>

                    </table>
					<a href="<?php echo $this->url('addStatusTransiton') ?>"><button class="btn btn-success">Zapisz</button></a>
                    </div>
			     </div>
			</div>
		</div>
	</div>
	</form>
