<div class="container under-top">	
	<div class="half-space-container">
	        <ol class="breadcrumb">
	                <li class="active"><?php echo $project->getName() ?> - Przegląd Projektu</li>
	        </ol>
	</div>
       	<div class="half-space-container text-right">
                <form class="form-group form-inline" role="form">
                        <div class="form-group">
                                <label for="inputProject" class="control-label">Pokaż projekt&nbsp;</label>
                                <select class="form-control" id="inputMainProjectList">
                                        <optgroup label="Projekty">
                                        	<?php foreach ($this->projects as $pro) { ?>
                                                <option value="<?php echo $pro->getId() ?>" <?php if($this->id == $pro->getId()){ echo "selected"; } ?>><?php echo $pro->getName() ?></option>
                                            <?php } ?>
                                        </optgroup>
                                </select>
                        </div>
                </form>
        </div>
</div>        
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
        <div class="container">
                <div class="tab-content col-md-6 " style="height:520px;">
  <span>                  
											<h3><?php echo $project->getName() ?></h3>
					<!--Nav tabs-->
					<ul class="nav nav-tabs">
					  <li class="active"><a href="#projekt" data-toggle="tab">Projekt</a></li>
					  <li><a href="#user" data-toggle="tab">Użytkownicy</a></li>
					  <li><a href="#taski" data-toggle="tab">Zadania</a></li>
					</ul>
						<!--Content tabs-->
						<div class="tab-content tab-content-white">					   
						<div id="projekt" class="tab-pane active">
						                    <h4><span class="glyphicon glyphicon-info-sign"></span> Szczegóły</h4>
						                    <div class="row show-grid row-with-space">
						                            <div class="col-md-2 col-md-3 details-label">ID:</div>
						                            <div class="col-md-2 col-md-6"><?php echo $project->getId() ?></div>
						                          
						                    </div>
						                    <div class="row">
						                           
						                            <div class="col-md-2 col-md-3 details-label">Status:</div>
						                            <div class="col-md-8 col-md-6"><?php echo $project->getProjectStatus() ?></div>
						                    </div>
						                    <h4><span class="glyphicon glyphicon-font"></span> Opis</h4>
						                    <?php echo $project->getDescription() ?>
						                                                
						 </div> 	
						<div id="user" class="tab-pane">					         
						     <table class="table table-bordered">
						            <thead>
						                   
						                   <tr>
													<th>Rola</th>	                                        
													<th>Imię i nazwisko</th>
						                            <th>Username</th>
						                            <th>Status</th>
						                           
						                     </tr>
						                   
						            </thead>
						            <tbody>
						                    <tr  class="table-clickable">
						                            <td>Kierownik projektu</td>
						                            <td>Adam Nowak</td>
						                            <td>@adnow</td>
						                            <td>Aktywny</td>
						                   
						                          </tr> 
				 							 <tr  class="table-clickable">
						                            <td>Developer</td>
						                            <td>Piotr Kowalski</td>
						                            <td>@alan</td>
						                            <td>Aktywny</td>
						                   
						                          </tr>

			</table></div>

			<div id="taski" class="tab-pane">
											<table class="table table-hover table-clickable issues-list-table">
                        <thead>
                                <tr>
                                        <th>Typ</th>
                                        <th>Klucz</th>
                                        <th>Podsumowanie</th>
                                        <th>Os. przypisana</th>
                                </tr>
                        </thead>
                        <tbody>
                        <?php $i=0;
                        foreach ($project->getIssues() as $issue) { ?>
                                <tr id="<?php echo $issue->getID() ?>">
									<td><span class="label label-default <?php echo "label-".$issue->getTracker() ?>"><?php echo $issue->getTracker() ?></span></td>	
									<td>#<?php echo $issue->getID() ?></td>
									<td><b><? echo $issue->getSubject();?></b></td>
                                    <td><?php foreach ($issue->getAssignedUsers() as $user){
                                                    $userName = $user->getFirstName()  . ' ' .  $user->getLastName() . '<br>';
                                                    if(!empty($user)){
                                                        echo $userName;
                                                    }else{
                                                        echo "brak";
                                                    }
                                    }?></td>
                                </tr>
                        <?php if(++$i == 5){break;}}?>
                        </tbody>
                </table>
				<a href="<?php echo $this->url('IssueList',array('project' => 1)) ?>">Wyświetl wszystkie zadania...</a>
		  </div> </div></div>
						        
       <div class="container">
              <div class="table-background-white col-md-5 col-md-offset-1" style="height:420px;">Ostatnie zmiany w projekcie 
					 <table class="table table-bordered">
						            <thead>
						                   
						                   <tr>
													<th>Zmiana</th>	 
													  <th>Opis</th>                                       
													<th>User</th>
						                            <th>Data</th>
						                         
						                           
						                     </tr>
						                   
						            </thead>
						            <tbody>
						                    <tr  class="table-clickable">
						                            <td>Task #BUG</td>
						                            <td>dodanie nowej funkcjonalności</td>
						                            <td>@adnow</td>
						                            <td>5.04.2014</td>
						                   
						                          </tr> 
				 							 <tr  class="table-clickable">
						                            <td>Dodanie usera</td>
						                            <td>dodanie nowej osoby do projektu</td>
						                            <td>@alan</td>
						                            <td>30.03.2014</td>
						                   
						                          </tr>

											</table>
								</div>
      
                </div>
               
                </div>  </div>
