<div class="container under-top">
    <div class="row">
        <div class="col-xs-12">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->url('FieldsList') ?>">Pola formularza</a></li>
                <li class="active">Dodaj nowe pole</li>
            </ol>
            <br />
        </div>
        </div>
</div>
<div class="jumbotron">
     <div class="container">
        <div class="col-xs-12">
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('AddField'));
            $form->prepare();
            echo $this->form()->openTag($form);

            ?>

            <div class="row">
                <div class="col-xs-12 text-right">
                    <button type="submit" class="btn btn-sm btn-success">
                        <span class="glyphicon glyphicon-ok"></span> Zapisz
                    </button>
                    <a class="btn btn-sm btn-warning">
                        <span class="glyphicon glyphicon-minus"></span> Anuluj
                    </a>
                    <hr />
                </div>

            </div>

            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-sm-3 text-right">
                        <?php echo $this->formLabel($form->get('name')); ?>
                    </div>
                    <div class="col-sm-9">
                        <?php echo $this->formText($form->get('name')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-3 text-right">
                        <?php echo $this->formLabel($form->get('types')); ?>
                    </div>
                    <div class="col-sm-9">
                        <?php echo $this->formSelect($form->get('types')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-3 text-right">
                        <?php echo $this->formLabel($form->get('minValue')); ?>
                    </div>
                    <div class="col-sm-9">
                        <?php echo $this->formText($form->get('minValue')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-3 text-right">
                        <?php echo $this->formLabel($form->get('maxValue')); ?>
                    </div>
                    <div class="col-sm-9">
                        <?php echo $this->formText($form->get('maxValue')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-9 col-sm-offset-3">
                        <div class="alert alert-info">
                            Informacja: Dla typu 'lista wartości', oddziel kolejne wartości przecinkiem.
                        </div>
                    </div>
                    <div class="col-sm-3 text-right">
                        <?php echo $this->formLabel($form->get('defaultValue')); ?>
                    </div>
                    <div class="col-sm-9">
                        <?php echo $this->formText($form->get('defaultValue')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-3 text-right">
                        <?php echo $this->formLabel($form->get('regex')); ?>
                    </div>
                    <div class="col-sm-9">
                        <?php echo $this->formText($form->get('regex')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-3 text-right">
                        <?php echo $this->formLabel($form->get('isRequired')); ?>
                    </div>
                    <div class="col-sm-9">
                        <?php echo $this->formCheckbox($form->get('isRequired')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-3 text-right">
                        <?php echo $this->formLabel($form->get('isForAll')); ?>
                    </div>
                    <div class="col-sm-9">
                        <?php echo $this->formCheckbox($form->get('isForAll')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-3 text-right">
                        <?php echo $this->formLabel($form->get('isHidden')); ?>
                    </div>
                    <div class="col-sm-9">
                        <?php echo $this->formCheckbox($form->get('isHidden')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-3 text-right">
                        <?php echo $this->formLabel($form->get('isFilter')); ?>
                    </div>
                    <div class="col-sm-9">
                        <?php echo $this->formCheckbox($form->get('isFilter')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-3 text-right">
                        <!--<?php echo $this->formLabel($form->get('projects')); ?>-->
                        <label class="control-label">Projekty</label>
                    </div>
                    <div class="col-sm-9">
                        <?php
                            if($form->get('projects') && count($form->get('projects')->getValueOptions()) > 0)
                                echo $this->formMultiCheckbox($form->get('projects'));
                            else
                                echo '<span class="btn btn-link disabled">Brak projektów.</span>';
                        ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-3 text-right">
                        <!--<?php echo $this->formLabel($form->get('trackers')); ?>-->
                        <label class="control-label">Trackery</label>
                    </div>
                    <div class="col-sm-9">
                        <?php
                        if($form->get('trackers') && count($form->get('trackers')->getValueOptions()) > 0)
                            echo $this->formMultiCheckbox($form->get('trackers'));
                        else
                            echo '<span class="btn btn-link disabled">Brak zdefiniowanych trackerów. Aby móc dodać pole, dodaj tracker.</span>';
                        ?>
                    </div>
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
