<div class="container under-top">
    <div class="row">
        <div class="col-xs-12">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->url('FieldsList') ?>">Pola formularza</a></li>
                <li class="active">Dodaj nowe pole</li>
            </ol>
            <br />
        </div>
        <div class="col-xs-12">
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('AddField'));
            $form->prepare();
            echo $this->form()->openTag($form);

            ?>

            <div class="row">
                <div class="col-xs-12 text-right">
                    <button type="submit" class="btn btn-sm btn-success">
                        <span class="glyphicon glyphicon-ok"></span> Zapisz
                    </button>
                    <a class="btn btn-sm btn-warning">
                        <span class="glyphicon glyphicon-minus"></span> Anuluj
                    </a>
                    <hr />
                </div>

            </div>

            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-sm-3 text-right">
                        <?php echo $this->formLabel($form->get('name')); ?>
                    </div>
                    <div class="col-sm-9">
                        <?php echo $this->formText($form->get('name')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-3 text-right">
                        <?php echo $this->formLabel($form->get('types')); ?>
                    </div>
                    <div class="col-sm-9">
                        <?php echo $this->formSelect($form->get('types')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-3 text-right">
                        <?php echo $this->formLabel($form->get('minValue')); ?>
                    </div>
                    <div class="col-sm-9">
                        <?php echo $this->formText($form->get('minValue')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-3 text-right">
                        <?php echo $this->formLabel($form->get('maxValue')); ?>
                    </div>
                    <div class="col-sm-9">
                        <?php echo $this->formText($form->get('maxValue')); ?>
                    </div>
                </div>
                <div class="form-group hidden">
                    <div class="col-sm-3">
                        <?php echo $this->formLabel($form->get('defaultValue')); ?>
                    </div>
                    <div class="col-sm-9">
                        <?php echo $this->formText($form->get('defaultValue')); ?>
                    </div>
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>