<!DOCTYPE html>
<html lang="pl">
<!--<html lang="pl" ng-app="<?php echo $this->config['ng-app'] ?>">-->
<head>
    <!-- start: Meta -->
    <meta charset="utf-8">
    <meta http-equiv='Content-Type' content="'application/xhtml xml;charset='utf-8'" />
    <?php echo $this->headTitle($this->config['title']) ?>
    <!-- end: Meta -->
    
    <!-- start: Mobile Specific -->
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <!-- end: Mobile Specific -->
	
    <!-- start: CSS -->
<?php foreach($this->config['css'] as $css){
    $this->headLink()->prependStylesheet($this->basePath() . $css );
}
echo $this->headLink(array('rel'  => 'shortcut icon', 'href' => $this->basePath().'/img/favicon.ico'),'prepend');
?>
    <!-- end: CSS -->

    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
    <?php echo $this->headScript()
        ->prependFile('http://html5shim.googlecode.com/svn/trunk/html5.js', 'text/javascript', array('conditional' => 'lt IE 9'))?>
    <?php echo $this->headLink()
        ->setStylesheet($this->basePath() . '/css/ie.css', 'screen', 'lt IE 9') ?>

    <!-- styles for IE9>
    <?php echo $this->headLink()
        ->setStylesheet($this->basePath() . '/css/ie9.css', 'screen', 'IE 9') ?>
    <! -->      
</head>

<body>

<!-- HEADER -->
    <div class="navbar navbar-inverse navbar-static-top navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Nawigacja</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand brand" href="/">PMS</a>
                <p class="navbar-text actual-project-cont">
                    <span class="navbar-brand-separator">/</span> 
                    <a href="<?php echo $this->url('ShowProject',array('project' => 1)) ?>" class="navbar-actual-project">Testowy Projekt nr 1</a>
                </p>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Projekty <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Aktualny projekt</li>
                            <li><a href="<?php echo $this->url('ShowProject',array('project' => 1)) ?>">Testowy Projekt nr 1</a></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Ostatnie projekty</li>
                            <li><a href="#">Most recent one</a></li>
                            <li><a href="#">Another recent project</a></li>
                            <li class="divider"></li>
                            <li><a href="?page=ProjectAll">Pokaż wszystkie projekty</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Zadania <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Aktualny projekt</li>
                            <li><a href="/1/issues">Lista zadań</a></li>
                            <li><a href="<?php echo $this->url('AddIssue',array('project' => 1)) ?>">Dodaj zadanie</a></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Filtry</li>
                            <li><a href="#">Zadania przypisane do mnie</a></li>
                            <li><a href="#">Ostatnio dodane zadania</a></li>
                            <li class="divider"></li>
                            <li><a href="?page=ListQueries">Zarządzaj filtrami</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administracja <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Użytkownicy</li>
                            <li><a href="?page=EditUser">Dodaj użytkownika</a></li>
                            <li><a href="?page=ListUsers">Lista użytkowników</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->url('FieldsList') ?>">Pola Formularza</a></li>
                            <li class="divider"></li>
                            <li><a href="?page=TypesOfIssues">Typy Zagadnień</a></li>
                            <li><a href="<?php echo $this->url('IssueStatus') ?>">Statusy zagadnień</a></li>
                            <li><a href="<?php echo $this->url('IssueCategory') ?>">Wyliczenia</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->url('CustomDict') ?>">Słowniki użytkownika</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->url('statusTransiton') ?>">Przejścia stanów</a></li>
                            <li><a href="<?php echo $this->url('fieldsPermission') ?>">Uprawnienia pól</a></li>
                        </ul>
                    </li>
                </ul>
                <div class="navbar-form navbar-left">
                    <A href="<?php echo $this->url('AddIssue',array('project' => 1)) ?>"><button type="button" class="btn btn-primary" id="add-task-btn">Dodaj zadanie</button></a>
                </div>
                <form class="navbar-form navbar-right" role="form">
                    <div class="form-group">
                        <input type="text" placeholder="Wpisz szukaną frazę..." class="form-control">
                    </div>
                    <button type="submit" class="btn btn-success">Szukaj</button>
                    <a href="?page=MyAccount" class="btn btn-info">
                        <span class="glyphicon glyphicon-user"></span>
                    </a>
                </form>
            </div><!--/.nav-collapse -->
        </div>
    </div>
<!-- /HEADER -->

<?php echo $this->content; ?>    
    
<?php foreach($this->config['js'] as $jsFile){
        $this->inlineScript()->appendFile($this->basePath() . $jsFile );
    }
    $this->inlineScript()->appendFile($this->basePath() . '/js/issues.js' );
    $this->inlineScript()->appendFile($this->basePath() . '/js/projects.js' );
    echo $this->inlineScript();
?>    

<!-- FOOTER -->
<div class="container">
    <footer>
        &copy; PMS 2014
    </footer>
</div> <!-- /container -->
<!-- FOOTER -->

</body>
</html>
