<div class="jumbotron">
        <div class="container">
            <div class="col-md-10 table-responsive table-background-white center-block">
                Siemaneiro
            </div>
            <div class="col-md-2">
                <strong>Kwerendy</strong>
                <ul class="list-unstyled">
                    <li><a href="#">Tylko otwarte</a></li>
                    <li><a href="#">Tylko przypisane do mnie</a></li>
                    <li><a href="#">Do przejrzenia</a></li>
                </ul>
            </div>
        </div>
</div>