	<div class="container">
		<ol class="breadcrumb">
			<li><a href="#">Strona Główna</a></li>
            		<li class="active">Uprawnienia pól</li>
		</ol>
	</div>
	<!-- Main jumbotron for a primary marketing message or call to action -->
	<div class="jumbotron">
        <ol class="breadcrumb container change-pos">                                 
            <li class="active">Uprawnienia pól</li>  
	<br>
	<br>

		<div class="half-space-container text-left">
                <form class="form-group form-inline" role="form">
                        <div class="form-group">
                                <label for="inputProject" class="control-label">Rola:&nbsp;</label>
                                <select class="form-control" id="inputProject">
                                   <?php
										foreach($roleList as $role){
											echo "<option value=" . $role->getId() . ">" . $role->getName() . "</option>";
										}
									?>
                                </select>
                        </div>

                        <div class="form-group">
                                <label for="inputProject" class="control-label">&nbsp;Typ zagadnienia:&nbsp;</label>
                                <select class="form-control" id="inputProject">
									<?php
										foreach($trackerList as $track){
											echo "<option value=" . $track->getId() . ">" . $track->getName() . "</option>";
										}
									?>
                                </select>
                        </div>

			<div class="form-group">
			<!--<label>&nbsp;&nbsp;&nbsp;</label>
			<button class="btn btn-info">Edytuj</button>-->
			</div>
                </form>
      		</div>
        </ol>  
		<div class="container">
			<div class="center-block table-responsive table-background-white" >
                <div class="center-block">
                    <div ng-app="app" ng-controller="Ctrl">
				    <table class="table table-striped">
                        
			
						<thead>
                            <tr class="breadcrumb">
							<th></th>
                                <?php
									foreach($issuelist as $issue){
										echo "<th>" . $issue->getName() . "</th>";
									}
								?>
								
                            </tr>
							<?php
								foreach($fields as $fp){
									echo "<tr>
									<th class='breadcrumb'>" . $fp->getField()->getName() . "</th>";			
									foreach($issuelist as $issueStatus){
										echo "<th>";
										echo "<select>";
										foreach($fieldPermission as $field){
											echo "<option value=" . $field->getId() . ">" . $field->getName() . "</option>";
										}
										echo "</select>";
										echo "</th>"; 
									}
									echo "</tr>";
								}
							?>
			    
                        </thead>

                    </table>
					<a href="<?php echo $this->url('addStatusTransiton') ?>"><button class="btn btn-success">Zapisz</button></a>
                    </div>
			     </div>
			</div>
		</div>
	</div>
