<!-- /BREADCRUMB-->
<div class="container under-top">
    <ol class="breadcrumb">
        <li class="active">Strona Główna</li>
    </ol>
</div>
<!-- /BREADCRUMB-->


<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
        <div class="container">
            <div class="col-md-12 table-responsive table-background-white center-block">
                <table class="table table-hover table-clickable table-condensed">
                        <thead>
                                <tr>
                                        <th>ID</th>
                                        <th>Nazwa</th>
                                        <th>Opis</th>
                                        <th>Status</th>
                                 </tr> 
                        </thead>
                        <tbody>
						<?php foreach ($this->projects as $project) { ?>
							<tr>
								<td><?php echo $project->getId() ?></td>
								<td><b><?php echo $project->getName() ?></b></td>
								<td><?php echo $project->getDescription() ?></td>
								<td><?php echo $project->getProjectStatus() ?></td>
							</tr>
						<?php }?>
                        </tbody>
                </table>
            </div>
        </div>
                </br>
         <div class="container">
                <div class="center-block table-responsive table-background-white" style="height:200px;">
                Tu powinna być lista ostatnich zdarzeń...  (Tracker Team GO GO GO!)
                </div>
        </div>
</div>