<div class="container under-top">
        <h1>Dzień dobry</h1>
</div>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
        <div class="container">
            <div class="col-md-10 table-responsive table-background-white center-block">
                <table class="table table-hover table-clickable table-condensed">
                        <thead>
                                <tr>
                                        <th>Typ</th>
                                        <th>Klucz</th>
                                        <th>Podsumowanie</th>
                                        <th>Os. przypisana</th>
                                        <th>Os. zgłaszająca</th>
                                        <th>Status</th>
                                        <th>Stan</th>
                                        <th>Utworzono</th>
                                        <th>Uaktualniono</th>
                                        <th>Deadline</th>
                                </tr>
                        </thead>
                        <tbody>
                                
                                <tr>
                                        <td>Bug</td>
                                        <td>#BUG-2</td>
                                        <td>Zaś coś nie działa</td>
                                        <td>Michał Flaming</td>
                                        <td>Grzegorz Pała</td>
                                        <td>Otwarty</td>
                                        <td>Niejasny</td>
                                        <td>30.01.2014</td>
                                        <td>04.02.2014</td>
                                        <td> -- </td>
                                </tr>
                        </tbody>
                </table>
            </div>
            <div class="col-md-2">
                <strong>Kwerendy</strong>
                <ul class="list-unstyled">
                    <li><a href="#">Tylko otwarte</a></li>
                    <li><a href="#">Tylko przypisane do mnie</a></li>
                    <li><a href="#">Do przejrzenia</a></li>
                </ul>
            </div>
        </div>
</div>