	<div class="container">
		<ol class="breadcrumb">
			<li><a href="#">Strona Główna</a></li>
            		<li class="active">Przejścia stanów</li>
		</ol>
	</div>
	<!-- Main jumbotron for a primary marketing message or call to action -->
	<div class="jumbotron">
	
        <ol class="breadcrumb container change-pos">                                 
            <li class="active">Przejścia stanów</li>  
	<br>
	<br>

		<div class="half-space-container text-left">
                <form class="form-group form-inline" role="form">
                        <div class="form-group">
                                <label for="inputProject" class="control-label">Rola:</label>
                                <select class="form-control" id="inputProject">
                                   <option>Manger</option>
                                   <option>Developer</option>
				   <option>Reporter</option>
				   <option>Non member</option>
				   <option>Anonymous</option>
                                </select>
                        </div>

                        <div class="form-group">
                                <label for="inputProject" class="control-label">&nbsp;Typ zagadnienia:&nbsp;</label>
                                <select class="form-control" id="inputProject">
                                   <option>Bug</option>
                                   <option>Extension</option>
				   <option>Support</option>
				   <option>Technical writing</option>
				   <option>Meeting</option>
                                </select>
                        </div>

			<div class="form-group">
			<!--<label>&nbsp;&nbsp;&nbsp;</label>
			<button class="btn btn-info">Edytuj</button>-->
			</div>
                </form>
      		</div>


                                  
        </ol>  
		<div class="container">
			<div class="center-block table-responsive table-background-white" >
                <div class="center-block">
                    <div ng-app="app" ng-controller="Ctrl">
				    <table class="table table-striped">
                        
			
			<thead>
                            <tr class="breadcrumb">
							<th></th>
                                <?php
									foreach($issuelist as $issue){
										echo "<th>" . $issue->getName() . "</th>";
									}
								?>
								
                            </tr>
							<?php
								foreach($issuelist as $issue){
									echo "<tr>
									<th class='breadcrumb'>" . $issue->getName() . "</th>";			
									foreach($issuelist as $issueStatus){
										echo "<th><input type='checkbox'> </th>";//" . $issueStatus->getName() . "
									}
									echo "</tr>";
								}
							?>
			    
                        </thead>

                    </table>
                    <button class="btn btn-success">Zapisz</button>
                    </div>
			     </div>
			</div>
		</div>
	</div>
