<style>
    li.header{
        margin-top: 20px;
    }
    .center-block.table-responsive.table-background-white {
padding-bottom: 20px;
}
tr:first-of-type i.fa.fa-sort-desc, tr:last-of-type i.fa.fa-sort-asc{
    cursor: not-allowed;
}
td p{
    width: 300px;
white-space: nowrap;
text-overflow: ellipsis;
text-align: left;
overflow: hidden;
font-size: 14px!important;
margin: 0px!important
}
</style>
    
	<div class="jumbotron">
        <ol class="breadcrumb container change-pos">                                 
            <li class="active header"></li>                                    
        </ol>  
            
		<div class="container">
			<div class="center-block table-responsive table-background-white" >
                
                                
                <div class="center-block">
                    <div ng-controller="Ctrl">
                        <h3>Kategorie dokumentów</h3>
				    <table class="table table-striped table-clickable">
                                        
                        <thead>
                            <tr>
                                <th style="width: 20%">Kategoria</th>
                                <th style="width: 30%">Opis</th>
                                <th style="width: 10%">Domyślna kategoria</th>
                                <th style="width: 10%">Aktywne</th>
                                <th style="width: 10%">Sortuj</th>
                                <th style="width: 15%">Akcja</th>
                            </tr>
                        </thead>
                                          
                        <tbody>
                            <?php foreach($issuelist as $issue) {
                               
                          
                          
                          if($issue->getIsActive(true)){
                            $active = '<i class="fa fa-check"></i>';
                          }
                          

                                                 echo '<tr>
		                        <td>'. $issue->getName('id').' </td> 
		                        <td><p>'. $issue->getDescription('id').' </p></td>
		                      <td>
                                    
                                    <span class="editable-wrap editable-checkbox ng-scope">
                                        <div class="editable-controls form-group">
                                           '. $issue->getIsDefault().'
                                            
                                           <div class="editable-error help-block ng-binding" ng-show="$error" ng-bind="$error" style="display: none;">                                                
                                           
                                            </div>                                                
                                        </div>
                                    </span>
                                </td>
                                <td>
                                    <span editable-checkbox="status.close" e-name="default" e-form="rowform" onbeforesave="checkName($data, close.id)" class="ng-scope ng-binding editable editable-hide editable-empty">
                                    
                                    </span>
                                    <span class="editable-wrap editable-checkbox ng-scope">
                                        <div class="editable-controls form-group">
                                            '. $issue->getIsActive().'
                                            <div class="editable-error help-block ng-binding" ng-show="$error" ng-bind="$error" style="display: none;">                                                
                                            </div>                                                
                                        </div>
                                    </span>
                                </td>
                                <td>
                                    
                                    <a href="'  . $this->url('DownIssueCategory', array('action'=>'downcategory', 'id'=>$issue->getId())). '"><i class="fa fa-sort-asc"></i></a>
                                    <a href="'  . $this->url('UpIssueCategory', array('action'=>'upcategory', 'id'=>$issue->getId())). '"><i class="fa fa-sort-desc"></i></a>
                                
                                </td>
		                 <td style="white-space: nowrap">
                                    <form editable-form="" name="rowform" onbeforesave="save($data, status.id)" ng-show="rowform.$visible" class="form-buttons form-inline ng-pristine ng-valid" shown="inserted == status">
                                        <a href="'  . $this->url('UpdateIssueCategory', array('action'=>'edit', 'id'=>$issue->getId())). '" class="btn btn-primary"><i class="fa fa-pencil-square-o"></i></a>
                                        <a href="'  . $this->url('DeleteIssueCategory', array('action'=>'delete', 'id'=>$issue->getId())). '"><button type="button" ng-disabled="rowform.$waiting" ng-click="rowform.$cancel()" class="btn btn-danger"><i class="fa fa-trash-o"></i></button> </a>
                                    </form>
                                     
                                </td>       

                            </tr>';
                                                }?>
                        </tbody>
                        
                    </table>
                         <a href="<?php echo $this->url('AddIssueCategory') ?>"><button type="submit" class="btn btn-success" ng-click="addstatus()"><i class="fa fa-plus-circle"></i> Stwórz kategorię</button></a>
                    
                    </div>
			
                </div>
                           
			</div>
                    
                    <div class="center-block table-responsive table-background-white" >
                
                                
                <div class="center-block">
                    <div ng-controller="Ctrl">
                        <h3>Priorytety zagadnień</h3>
				    <table class="table table-striped table-clickable">
                                        
                        <thead>
                            <tr>
                                <th style="width: 20%">Priorytet</th>
                                <th style="width: 30%">Opis</th>
                                <th style="width: 10%">Domyślny priorytet</th>
                                <th style="width: 10%">Aktywne</th>
                                <th style="width: 10%">Sortuj</th>
                                <th style="width: 15%">Akcja</th>
                            </tr>
                        </thead>
                                          
                        <tbody>
                            <?php foreach($issuepriority as $issue) {
                               
                          
                          
                          if($issue->getIsActive(true)){
                            $active = '<i class="fa fa-check"></i>';
                          }

                                                 echo '<tr>
		                        <td>'. $issue->getName('id').' </td> 
		                        <td><p>'. $issue->getDescription('id').' </p></td>
		                      <td>
                                    
                                    <span class="editable-wrap editable-checkbox ng-scope">
                                        <div class="editable-controls form-group">
                                           '. $issue->getIsDefault().'
                                            
                                           <div class="editable-error help-block ng-binding" ng-show="$error" ng-bind="$error" style="display: none;">                                                
                                           
                                            </div>                                                
                                        </div>
                                    </span>
                                </td>
                                <td>
                                    <span editable-checkbox="status.close" e-name="default" e-form="rowform" onbeforesave="checkName($data, close.id)" class="ng-scope ng-binding editable editable-hide editable-empty">
                                    
                                    </span>
                                    <span class="editable-wrap editable-checkbox ng-scope">
                                        <div class="editable-controls form-group">
                                            '. $issue->getIsActive().'
                                            <div class="editable-error help-block ng-binding" ng-show="$error" ng-bind="$error" style="display: none;">                                                
                                            </div>                                                
                                        </div>
                                    </span>
                                </td>
                                <td>
                                    <a href="'  . $this->url('DownIssuePriority', array('action'=>'downpriority', 'id'=>$issue->getId())). '"><i class="fa fa-sort-asc"></i></a>
                                    <a href="'  . $this->url('UpIssuePriority', array('action'=>'uppriority', 'id'=>$issue->getId())). '"><i class="fa fa-sort-desc"></i></a>
                                
                                </td>
		                 <td style="white-space: nowrap">
                                    <form editable-form="" name="rowform" onbeforesave="save($data, status.id)" ng-show="rowform.$visible" class="form-buttons form-inline ng-pristine ng-valid" shown="inserted == status">
                                        <a href="'  . $this->url('UpdateIssuePriority', array('action'=>'edit', 'id'=>$issue->getId())). '" class="btn btn-primary"><i class="fa fa-pencil-square-o"></i></a>
                                        <a href="'  . $this->url('DeleteIssuePriority', array('action'=>'delete', 'id'=>$issue->getId())). '"><button type="button" ng-disabled="rowform.$waiting" ng-click="rowform.$cancel()" class="btn btn-danger"><i class="fa fa-trash-o"></i></button> </a>
                                    </form>
                                     
                                </td>       

                            </tr>';
                                                }?>
                        </tbody>
                        
                    </table>
                         <a href="<?php echo $this->url('AddIssuePriority') ?>"><button type="submit" class="btn btn-success" ng-click="addstatus()"><i class="fa fa-plus-circle"></i> Stwórz priorytet</button></a>
                    
                    </div>
			
                </div>
                           
			</div>
                    
                    <div class="center-block table-responsive table-background-white" >
                
                                
                <div class="center-block">
                    <div ng-controller="Ctrl">
                        <h3>Działania (śledzenie czasu)</h3>
				    <table class="table table-striped table-clickable">
                                        
                        <thead>
                            <tr>
                                <th style="width: 20%">Działanie</th>
                                <th style="width: 30%">Opis</th>
                                <th style="width: 10%">Domyślne działanie</th>
                                <th style="width: 10%">Aktywne</th>
                                <th style="width: 10%">Sortuj</th>
                                <th style="width: 15%">Akcja</th>
                            </tr>
                        </thead>
                                          
                        <tbody>
                            <?php foreach($issueactivity as $issue) {
                               
                          
                          
                          if($issue->getIsActive(true)){
                            $active = '<i class="fa fa-check"></i>';
                          }
                          
                     
                                
                               
                                                 echo '<tr>
		                        <td>'. $issue->getName('id').' </td> 
		                        <td><p>'. $issue->getDescription('id').' </p></td>
		                      <td>
                                    
                                    <span class="editable-wrap editable-checkbox ng-scope">
                                        <div class="editable-controls form-group">
                                           '. $issue->getIsDefault().'
                                            
                                           <div class="editable-error help-block ng-binding" ng-show="$error" ng-bind="$error" style="display: none;">                                                
                                           
                                            </div>                                                
                                        </div>
                                    </span>
                                </td>
                                <td>
                                    <span editable-checkbox="status.close" e-name="default" e-form="rowform" onbeforesave="checkName($data, close.id)" class="ng-scope ng-binding editable editable-hide editable-empty">
                                    
                                    </span>
                                    <span class="editable-wrap editable-checkbox ng-scope">
                                        <div class="editable-controls form-group">
                                            '. $issue->getIsActive().'
                                            <div class="editable-error help-block ng-binding" ng-show="$error" ng-bind="$error" style="display: none;">                                                
                                            </div>                                                
                                        </div>
                                    </span>
                                </td>
                                <td>
                                    <a href="'  . $this->url('DownIssueActivity', array('action'=>'downactivity', 'id'=>$issue->getId())). '"><i class="fa fa-sort-asc"></i></a>
                                    <a href="'  . $this->url('UpIssueActivity', array('action'=>'upactivity', 'id'=>$issue->getId())). '"><i class="fa fa-sort-desc"></i></a>
                                 
                                </td>
		                 <td style="white-space: nowrap">
                                    <form editable-form="" name="rowform" onbeforesave="save($data, status.id)" ng-show="rowform.$visible" class="form-buttons form-inline ng-pristine ng-valid" shown="inserted == status">
                                        <a href="'  . $this->url('UpdateIssueActivity', array('action'=>'edit', 'id'=>$issue->getId())). '" class="btn btn-primary"><i class="fa fa-pencil-square-o"></i></a>
                                        <a href="'  . $this->url('DeleteIssueActivity', array('action'=>'delete', 'id'=>$issue->getId())). '"><button type="button" ng-disabled="rowform.$waiting" ng-click="rowform.$cancel()" class="btn btn-danger"><i class="fa fa-trash-o"></i></button> </a>
                                    </form>
                                     
                                </td>       

                            </tr>';
                                                }?>
                        </tbody>
                        
                    </table>
                         <a href="<?php echo $this->url('AddIssueActivity') ?>"><button type="submit" class="btn btn-success" ng-click="addstatus()"><i class="fa fa-plus-circle"></i> Stwórz działanie</button></a>
                    
                    </div>
			
                </div>
                           
			</div>
                    
                    
		</div>
            
      
            
	</div>



    


